"""agent006 completion — Generate shell completion scripts.

Usage:
    agent006 completion bash     # Print bash completion script
    agent006 completion zsh      # Print zsh completion script
    agent006 completion fish     # Print fish completion script
    agent006 completion install  # Auto-install for current shell
"""

import os
from pathlib import Path

import click

# Completion script templates — generated by Click 8.x, embedded to avoid
# subprocess overhead and capture issues.
_BASH_SCRIPT = r"""
%(complete_func)s() {
    local IFS=$'\n'
    COMPREPLY=( $( env COMP_WORDS="${COMP_WORDS[*]}" \
                   COMP_CWORD=$COMP_CWORD \
                   %(complete_var)s=bash_complete $1 ) )
    return 0
}

%(complete_func)ssetup() {
    complete -o default -F %(complete_func)s %(prog_name)s
}

%(complete_func)ssetup;
""".strip()

_ZSH_SCRIPT = r"""
#compdef %(prog_name)s

%(complete_func)s() {
    local -a completions
    local -a completions_with_descriptions
    local -a response
    (( ! $+commands[%(prog_name)s] )) && return 1

    response=("${(@f)$(env COMP_WORDS="${words[*]}" COMP_CWORD=$((CURRENT-1)) %(complete_var)s=zsh_complete %(prog_name)s)}")

    for type key descr in ${response}; do
        if [[ "$type" == "plain" ]]; then
            if [[ "$descr" == "_" ]]; then
                completions+=("$key")
            else
                completions_with_descriptions+=("$key":"$descr")
            fi
        elif [[ "$type" == "dir" ]]; then
            _path_files -/
        elif [[ "$type" == "file" ]]; then
            _path_files -f
        fi
    done

    if [ -n "$completions_with_descriptions" ]; then
        _describe -V unsorted completions_with_descriptions -U
    fi

    if [ -n "$completions" ]; then
        compadd -U -V unsorted -a completions
    fi
}

if [[ $zsh_eval_context[-1] == loadautofun ]]; then
    # autoload from fpath
    %(complete_func)s "$@"
else
    compdef %(complete_func)s %(prog_name)s
fi
""".strip()

_FISH_SCRIPT = r"""
complete -c %(prog_name)s -f -a "(env %(complete_var)s=fish_complete COMP_WORDS=(commandline -cp) COMP_CWORD=(commandline -t) %(prog_name)s)"
""".strip()


def _render_script(template: str) -> str:
    """Render a completion script template with agent006-specific values."""
    return template % {
        "complete_func": "_agent006_completion",
        "complete_var": "_AGENT006_COMPLETE",
        "prog_name": "agent006",
    }


@click.group()
def completion():
    """Generate shell completion scripts for agent006.

    \b
    Quick setup (add to your shell profile):

        # bash (~/.bashrc)
        eval "$(_AGENT006_COMPLETE=bash_source agent006)"

        # zsh (~/.zshrc)
        eval "$(_AGENT006_COMPLETE=zsh_source agent006)"

        # fish (~/.config/fish/config.fish)
        _AGENT006_COMPLETE=fish_source agent006 | source
    """


@completion.command()
def bash():
    """Print bash completion script.

    \b
    Usage:
        eval "$(agent006 completion bash)"
        # Or append to profile:
        agent006 completion bash >> ~/.bashrc
    """
    click.echo(_render_script(_BASH_SCRIPT))


@completion.command()
def zsh():
    """Print zsh completion script.

    \b
    Usage:
        eval "$(agent006 completion zsh)"
        # Or append to profile:
        agent006 completion zsh >> ~/.zshrc
    """
    click.echo(_render_script(_ZSH_SCRIPT))


@completion.command()
def fish():
    """Print fish completion script.

    \b
    Usage:
        agent006 completion fish > ~/.config/fish/completions/agent006.fish
    """
    click.echo(_render_script(_FISH_SCRIPT))


@completion.command()
def install():
    """Auto-detect shell and install completions.

    Detects your current shell and appends the completion script
    to the appropriate profile file.
    """
    shell = _detect_shell()
    if not shell:
        click.secho("Could not detect your shell. Use one of:", fg="red")
        click.echo("  agent006 completion bash")
        click.echo("  agent006 completion zsh")
        click.echo("  agent006 completion fish")
        raise SystemExit(1)

    click.echo(f"Detected shell: {shell}")

    if shell == "bash":
        profile = Path.home() / ".bashrc"
        line = 'eval "$(_AGENT006_COMPLETE=bash_source agent006)"'
    elif shell == "zsh":
        profile = Path.home() / ".zshrc"
        line = 'eval "$(_AGENT006_COMPLETE=zsh_source agent006)"'
    elif shell == "fish":
        profile = Path.home() / ".config" / "fish" / "completions" / "agent006.fish"
        line = None  # Fish uses a completions file with the script directly
    else:
        click.secho(f"Unsupported shell: {shell}", fg="red")
        raise SystemExit(1)

    # Check if already installed
    if profile.exists():
        existing = profile.read_text()
        if "_AGENT006_COMPLETE" in existing:
            click.secho(f"Completions already installed in {profile}", fg="green")
            return

    if shell == "fish":
        # Fish: write completions file
        profile.parent.mkdir(parents=True, exist_ok=True)
        script = _render_script(_FISH_SCRIPT)
        profile.write_text(script + "\n")
        click.secho(f"Completions written to {profile}", fg="green")
    else:
        # Bash/zsh: append eval one-liner to profile
        with open(profile, "a") as f:
            f.write(f"\n# agent006 shell completions\n{line}\n")
        click.secho(f"Completions added to {profile}", fg="green")
        click.echo(f"Run: source {profile}")


def _detect_shell() -> str | None:
    """Detect the current shell."""
    shell = os.environ.get("SHELL", "")
    if "zsh" in shell:
        return "zsh"
    elif "bash" in shell:
        return "bash"
    elif "fish" in shell:
        return "fish"
    return None
