"""nemo-oo completion — Generate shell completion scripts.

Usage:
    nemo-oo completion bash     # Print bash completion script
    nemo-oo completion zsh      # Print zsh completion script
    nemo-oo completion fish     # Print fish completion script
    nemo-oo completion install  # Auto-install for current shell
"""

import os
from pathlib import Path

import click

# Completion script templates — generated by Click 8.x, embedded to avoid
# subprocess overhead and capture issues.
_BASH_SCRIPT = r"""
%(complete_func)s() {
    local IFS=$'\n'
    COMPREPLY=( $( env COMP_WORDS="${COMP_WORDS[*]}" \
                   COMP_CWORD=$COMP_CWORD \
                   %(complete_var)s=bash_complete $1 ) )
    return 0
}

%(complete_func)ssetup() {
    complete -o default -F %(complete_func)s %(prog_name)s
}

%(complete_func)ssetup;
""".strip()

_ZSH_SCRIPT = r"""
#compdef %(prog_name)s

%(complete_func)s() {
    local -a completions
    local -a completions_with_descriptions
    local -a response
    (( ! $+commands[%(prog_name)s] )) && return 1

    response=("${(@f)$(env COMP_WORDS="${words[*]}" COMP_CWORD=$((CURRENT-1)) %(complete_var)s=zsh_complete %(prog_name)s)}")

    for type key descr in ${response}; do
        if [[ "$type" == "plain" ]]; then
            if [[ "$descr" == "_" ]]; then
                completions+=("$key")
            else
                completions_with_descriptions+=("$key":"$descr")
            fi
        elif [[ "$type" == "dir" ]]; then
            _path_files -/
        elif [[ "$type" == "file" ]]; then
            _path_files -f
        fi
    done

    if [ -n "$completions_with_descriptions" ]; then
        _describe -V unsorted completions_with_descriptions -U
    fi

    if [ -n "$completions" ]; then
        compadd -U -V unsorted -a completions
    fi
}

if [[ $zsh_eval_context[-1] == loadautofun ]]; then
    # autoload from fpath
    %(complete_func)s "$@"
else
    compdef %(complete_func)s %(prog_name)s
fi
""".strip()

_FISH_SCRIPT = r"""
complete -c %(prog_name)s -f -a "(env %(complete_var)s=fish_complete COMP_WORDS=(commandline -cp) COMP_CWORD=(commandline -t) %(prog_name)s)"
""".strip()


def _render_script(template: str) -> str:
    """Render a completion script template with nemo_oo_agents-specific values."""
    return template % {
        "complete_func": "_nemo_oo_agents_completion",
        "complete_var": "_NEMO_OO_AGENTS_COMPLETE",
        "prog_name": "nemo-oo",
    }


@click.group()
def completion():
    """Generate shell completion scripts for nemo_oo_agents.

    \b
    Quick setup (add to your shell profile):

        # bash (~/.bashrc)
        eval "$(_NEMO_OO_AGENTS_COMPLETE=bash_source nemo-oo)"

        # zsh (~/.zshrc)
        eval "$(_NEMO_OO_AGENTS_COMPLETE=zsh_source nemo-oo)"

        # fish (~/.config/fish/config.fish)
        _NEMO_OO_AGENTS_COMPLETE=fish_source nemo-oo | source
    """


@completion.command()
def bash():
    """Print bash completion script.

    \b
    Usage:
        eval "$(nemo-oo completion bash)"
        # Or append to profile:
        nemo-oo completion bash >> ~/.bashrc
    """
    click.echo(_render_script(_BASH_SCRIPT))


@completion.command()
def zsh():
    """Print zsh completion script.

    \b
    Usage:
        eval "$(nemo-oo completion zsh)"
        # Or append to profile:
        nemo-oo completion zsh >> ~/.zshrc
    """
    click.echo(_render_script(_ZSH_SCRIPT))


@completion.command()
def fish():
    """Print fish completion script.

    \b
    Usage:
        nemo-oo completion fish > ~/.config/fish/completions/nemo-oo.fish
    """
    click.echo(_render_script(_FISH_SCRIPT))


@completion.command()
def install():
    """Auto-detect shell and install completions.

    Detects your current shell and appends the completion script
    to the appropriate profile file.
    """
    shell = _detect_shell()
    if not shell:
        click.secho("Could not detect your shell. Use one of:", fg="red")
        click.echo("  nemo-oo completion bash")
        click.echo("  nemo-oo completion zsh")
        click.echo("  nemo-oo completion fish")
        raise SystemExit(1)

    click.echo(f"Detected shell: {shell}")

    if shell == "bash":
        profile = Path.home() / ".bashrc"
        line = 'eval "$(_NEMO_OO_AGENTS_COMPLETE=bash_source nemo-oo)"'
    elif shell == "zsh":
        profile = Path.home() / ".zshrc"
        line = 'eval "$(_NEMO_OO_AGENTS_COMPLETE=zsh_source nemo-oo)"'
    elif shell == "fish":
        profile = Path.home() / ".config" / "fish" / "completions" / "nemo-oo.fish"
        line = None  # Fish uses a completions file with the script directly
    else:
        click.secho(f"Unsupported shell: {shell}", fg="red")
        raise SystemExit(1)

    # Check if already installed
    if profile.exists():
        existing = profile.read_text()
        if "_NEMO_OO_AGENTS_COMPLETE" in existing:
            click.secho(f"Completions already installed in {profile}", fg="green")
            return

    if shell == "fish":
        # Fish: write completions file
        profile.parent.mkdir(parents=True, exist_ok=True)
        script = _render_script(_FISH_SCRIPT)
        profile.write_text(script + "\n")
        click.secho(f"Completions written to {profile}", fg="green")
    else:
        # Bash/zsh: append eval one-liner to profile
        with open(profile, "a") as f:
            f.write(f"\n# nemo-oo shell completions\n{line}\n")
        click.secho(f"Completions added to {profile}", fg="green")
        click.echo(f"Run: source {profile}")


def _detect_shell() -> str | None:
    """Detect the current shell."""
    shell = os.environ.get("SHELL", "")
    if "zsh" in shell:
        return "zsh"
    elif "bash" in shell:
        return "bash"
    elif "fish" in shell:
        return "fish"
    return None
