# SPDX-FileCopyrightText: Copyright (c) 2025, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""E2E integration test: archival fires on ContextWindowExceededError.

Phase 1: Load ~50% of fixture events → successful call → learns calibration ratio.
Phase 2: Load remaining events (overflow) → call fails → archival → rebuild → succeed.
Phase 3: Verify events archived down to ~60% utilization target.

Fixture generated by: python tests/integration/generate_archival_fixture.py

Run with:
    pytest -m integration tests/integration/test_archival_on_error_e2e.py -v
"""

import gzip
import json
import os
from pathlib import Path

import pytest

from nemo_oo_agents import Agent
from nemo_oo_agents.context_blocks.events import ResultStatus, ToolCallEvent, ToolResult
from nemo_oo_agents.events import PythonOutput, Summary
from nemo_oo_agents.runtime.actor import _ARCHIVE_TARGET_UTILIZATION
from nemo_oo_agents.unifiedllm import CompletionClient

_FIXTURE_PATH = Path(__file__).parent / "fixtures" / "archival_95pct.json.gz"
_API_BASE = "https://inference-api.nvidia.com/v1"
_API_KEY_ENV = "NVIDIA_INTERNAL_API_KEY"

_EVENT_TYPES = {
    "ToolCallEvent": ToolCallEvent,
    "PythonOutput": PythonOutput,
}


def _load_fixture():
    """Load pre-generated events from the compressed fixture."""
    with gzip.open(_FIXTURE_PATH, "rt") as f:
        return json.load(f)


def _hydrate_events(agent, event_entries):
    """Load a list of event entries into the agent's event manager."""
    for entry in event_entries:
        event_cls = _EVENT_TYPES.get(entry["event_type"])
        if event_cls is None:
            continue
        ev = event_cls.model_validate(entry["data"])
        agent.event_manager.add(ev)


@pytest.mark.integration
class TestArchivalOnContextErrorE2E:
    """E2E: succeed at ~50% → calibrate → overflow → archive → succeed."""

    @pytest.mark.asyncio
    async def test_full_archival_lifecycle(self):
        api_key = os.environ.get(_API_KEY_ENV, "")
        if not api_key:
            pytest.skip(f"{_API_KEY_ENV} not set")
        if not _FIXTURE_PATH.exists():
            pytest.skip(f"Fixture not found: {_FIXTURE_PATH}")

        fixture_data = _load_fixture()
        ctx_window = fixture_data["context_window"]
        all_events = fixture_data["events"]

        # The fixture stores the model without litellm provider prefix.
        model_name = "openai/" + fixture_data["model"]

        llm = CompletionClient(
            model=model_name,
            api_base=_API_BASE,
            api_key=api_key,
            temperature=0,
        )
        if llm.context_window is None:
            llm._registry_config = {"context_window": ctx_window}

        class A(Agent, llm=llm):
            async def respond(self, prompt: str) -> str:
                """Respond to {prompt}."""
                ...

        agent = A()

        # Subscribe to Summary events (emitted by archival)
        summary_events: list = []
        agent.event_manager.on("Summary", lambda ev: summary_events.append(ev))

        # ── Phase 1: Load ~20% of events → successful call ─────────
        # 800 total events, load ~160 (20%). This should be well under
        # the context window and the call should succeed. The successful
        # call lets the runtime learn the calibration ratio from
        # response.usage.prompt_tokens.
        phase1_count = len(all_events) // 5  # 20% of events
        _hydrate_events(agent, all_events[:phase1_count])

        n_phase1 = len(list(agent.event_manager.keys()))
        assert n_phase1 == phase1_count

        result1 = await agent.respond("Say hello in one word.")
        assert result1, "Phase 1: call should succeed with 20% fill"
        assert len(summary_events) == 0, (
            f"Phase 1: no archival expected, got {len(summary_events)}"
        )

        # Calibration ratio should have been learned from the successful call
        ratio = agent.runtime._token_calibration_ratio
        assert ratio is not None, (
            "Phase 1: calibration ratio should be learned from response.usage"
        )
        assert ratio > 0, f"Calibration ratio should be positive, got {ratio}"

        # ── Phase 2: Load ALL remaining events → overflow ──────────
        # Add the rest of the events. This pushes way past the context window.
        # The call should fail with ContextWindowExceededError, trigger archival,
        # rebuild messages, and retry successfully.
        _hydrate_events(agent, all_events[phase1_count:])
        n_phase2 = len(list(agent.event_manager.keys()))
        assert n_phase2 > n_phase1, "Should have more events after loading remainder"

        summary_events.clear()

        result2 = await agent.respond("Say goodbye in one word.")
        assert result2, "Phase 2: call should succeed after archival + retry"

        # ── Phase 3: Verify archival ───────────────────────────────
        n_after = len(list(agent.event_manager.keys()))

        assert len(summary_events) >= 1, (
            f"Archival should emit Summary events, got {len(summary_events)}. "
            f"Events: {n_phase2} → {n_after}"
        )
        ev = summary_events[0]
        assert "context-window API error" in ev.summary_text, (
            f"Summary should mention API error: {ev.summary_text[:200]}"
        )
        assert ev.children_tags, "Summary must reference archived child tags"

        # Events should have decreased significantly
        assert n_after < n_phase2, (
            f"Archival should reduce events: {n_after} >= {n_phase2}"
        )

        # Verify archival targeted ~60% utilization
        # The archival cap uses the learned ratio:
        # cap = ctx_window * 0.70 / ratio
        # target = cap * 0.60
        effective_cap = int(ctx_window * 0.70 / max(ratio, 1.0))
        target_tok = int(effective_cap * _ARCHIVE_TARGET_UTILIZATION)

        # Rough check: archived at least 40% of events (going from 100%+ to 60%)
        archived_fraction = (n_phase2 - n_after) / n_phase2
        assert archived_fraction > 0.30, (
            f"Expected significant archival: only {archived_fraction:.0%} archived "
            f"({n_phase2} → {n_after})"
        )
