# SPDX-FileCopyrightText: Copyright (c) 2025, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""E2E integration test: archival fires on ContextWindowExceededError.

Loads a pre-generated fixture (~95% context fill) and calls the LLM.
Without the proactive clamp, the API sees all events and rejects if
context exceeds the window. The recovery path archives + rebuilds + retries.

Fixture generated by: python tests/integration/generate_archival_fixture.py

Run with:
    pytest -m integration tests/integration/test_archival_on_error_e2e.py -v
"""

import gzip
import json
import os
from pathlib import Path

import pytest

from nemo_oo_agents import Agent
from nemo_oo_agents.context_blocks.events import ResultStatus, ToolCallEvent, ToolResult
from nemo_oo_agents.events import PythonOutput, Summary
from nemo_oo_agents.runtime.actor import _ARCHIVE_TARGET_UTILIZATION
from nemo_oo_agents.unifiedllm import CompletionClient

_FIXTURE_PATH = Path(__file__).parent / "fixtures" / "archival_95pct.json.gz"
_API_BASE = "https://inference-api.nvidia.com/v1"
_API_KEY_ENV = "NVIDIA_INTERNAL_API_KEY"

# Event type registry for deserialization
_EVENT_TYPES = {
    "ToolCallEvent": ToolCallEvent,
    "PythonOutput": PythonOutput,
}


def _load_fixture():
    """Load pre-generated events from the compressed fixture."""
    with gzip.open(_FIXTURE_PATH, "rt") as f:
        return json.load(f)


def _hydrate_events(agent, fixture_data):
    """Load events from fixture into the agent's event manager."""
    for entry in fixture_data["events"]:
        event_cls = _EVENT_TYPES.get(entry["event_type"])
        if event_cls is None:
            continue
        ev = event_cls.model_validate(entry["data"])
        agent.event_manager.add(ev)


@pytest.mark.integration
class TestArchivalOnContextErrorE2E:
    """E2E: load fixture at 95% → call LLM → API rejects → archive → retry → succeed."""

    @pytest.mark.asyncio
    async def test_full_archival_lifecycle(self):
        api_key = os.environ.get(_API_KEY_ENV, "")
        if not api_key:
            pytest.skip(f"{_API_KEY_ENV} not set")
        if not _FIXTURE_PATH.exists():
            pytest.skip(f"Fixture not found: {_FIXTURE_PATH}")

        fixture_data = _load_fixture()
        ctx_window = fixture_data["context_window"]

        # The fixture stores the model without litellm provider prefix.
        model_name = "openai/" + fixture_data["model"]

        llm = CompletionClient(
            model=model_name,
            api_base=_API_BASE,
            api_key=api_key,
            temperature=0,
        )
        # litellm may not know this model — inject context_window.
        if llm.context_window is None:
            llm._registry_config = {"context_window": ctx_window}

        class A(Agent, llm=llm):
            async def respond(self, prompt: str) -> str:
                """Respond to {prompt}."""
                ...

        agent = A()

        # ── Load fixture: ~250K litellm tokens (95% of 262K) ───────
        _hydrate_events(agent, fixture_data)
        n_events_loaded = len(list(agent.event_manager.keys()))
        assert n_events_loaded == fixture_data["n_events"], (
            f"Loaded {n_events_loaded}, expected {fixture_data['n_events']}"
        )

        # Subscribe to Summary events (emitted by archival)
        summary_events: list = []
        agent.event_manager.on("Summary", lambda ev: summary_events.append(ev))

        # ── Call the LLM ───────────────────────────────────────────
        # No proactive clamp — all 250K litellm tokens go to the API.
        # The API sees ~250K * 1.6x ratio ≈ 400K real tokens > 262K limit.
        # → ContextWindowExceededError → archive → rebuild → retry → succeed
        result = await agent.respond("Say hello in one word.")
        assert result, "Call should succeed after recovery"

        # ── Verify archival fired ──────────────────────────────────
        n_events_after = len(list(agent.event_manager.keys()))

        assert len(summary_events) >= 1, (
            f"Archival should emit Summary events, got {len(summary_events)}. "
            f"Events before={n_events_loaded}, after={n_events_after}"
        )
        ev = summary_events[0]
        assert "context-window API error" in ev.summary_text, (
            f"Summary should mention API error: {ev.summary_text[:200]}"
        )
        assert ev.children_tags, "Summary must reference archived child tags"

        # Events should have decreased (archival removes oldest)
        assert n_events_after < n_events_loaded, (
            f"Archival should reduce events: {n_events_after} >= {n_events_loaded}"
        )

        # ── Verify utilization target ──────────────────────────────
        # After archival, the event store should be near 60% of the cap.
        ratio = agent.runtime._token_calibration_ratio or 1.0
        effective_cap = int(ctx_window * 0.70 / max(ratio, 1.0))
        target_tok = int(effective_cap * _ARCHIVE_TARGET_UTILIZATION)

        # Rough check: archived at least 20% of events
        archived_fraction = (n_events_loaded - n_events_after) / n_events_loaded
        assert archived_fraction > 0.20, (
            f"Should archive significant fraction: only {archived_fraction:.1%} archived"
        )

        # ── Verify calibration ratio learned ───────────────────────
        ratio = agent.runtime._token_calibration_ratio
        if ratio is not None:
            assert ratio > 0, f"Ratio should be positive: {ratio}"
            # Nemotron Nano has ~1.6x ratio (litellm undercounts)
            assert ratio > 1.0, (
                f"Expected ratio > 1.0 (litellm undercounts), got {ratio:.2f}"
            )
