# SPDX-FileCopyrightText: Copyright (c) 2025, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""E2E integration test: archival fires only on ContextWindowExceededError.

Uses a pre-generated fixture (95% context fill) to avoid the slow fill phase.
Fixture generated by: python tests/integration/generate_archival_fixture.py

Run with:
    pytest -m integration tests/integration/test_archival_on_error_e2e.py -v
"""

import gzip
import json
import os
from pathlib import Path

import pytest

from nemo_oo_agents import Agent
from nemo_oo_agents.context_blocks.events import ResultStatus, ToolCallEvent, ToolResult
from nemo_oo_agents.events import PythonOutput, Summary
from nemo_oo_agents.runtime.actor import (
    _ARCHIVE_TARGET_UTILIZATION,
    _current_llm_var,
    _current_method_var,
)
from nemo_oo_agents.unifiedllm import CompletionClient

_FIXTURE_PATH = Path(__file__).parent / "fixtures" / "archival_95pct.json.gz"
_API_BASE = "https://inference-api.nvidia.com/v1"
_API_KEY_ENV = "NVIDIA_INTERNAL_API_KEY"

# Event type registry for deserialization
_EVENT_TYPES = {
    "ToolCallEvent": ToolCallEvent,
    "PythonOutput": PythonOutput,
}


def _load_fixture():
    """Load pre-generated events from the compressed fixture."""
    with gzip.open(_FIXTURE_PATH, "rt") as f:
        data = json.load(f)
    return data


def _hydrate_events(agent, fixture_data):
    """Load events from fixture into the agent's event manager."""
    for entry in fixture_data["events"]:
        event_cls = _EVENT_TYPES.get(entry["event_type"])
        if event_cls is None:
            continue
        ev = event_cls.model_validate(entry["data"])
        agent.event_manager.add(ev)


def _add_overflow_events(agent, n_events: int = 200, payload_words: int = 300):
    """Add extra events to push past the context window."""
    base = len(list(agent.event_manager.keys()))
    for i in range(n_events):
        idx = base + i
        tc_id = f"overflow_{idx}"
        payload = f"overflow_data_{idx} " * payload_words
        agent.event_manager.add(
            ToolCallEvent(
                tool_call_id=tc_id,
                name="execute_python",
                arguments={"code": payload},
                result=ToolResult(
                    tool_call_id=tc_id,
                    content=payload,
                    result_status=ResultStatus.COMPLETE,
                ),
            )
        )
        agent.event_manager.add(
            PythonOutput(
                tool_call_id=tc_id,
                execution_count=idx,
                stdout=payload,
                stderr="",
                execution_status=ResultStatus.COMPLETE,
            )
        )


@pytest.mark.integration
class TestArchivalOnContextErrorE2E:
    """E2E: load 95% fixture → succeed → overflow to 105% → fail → archive → succeed."""

    @pytest.mark.asyncio
    async def test_full_archival_lifecycle(self):
        api_key = os.environ.get(_API_KEY_ENV, "")
        if not api_key:
            pytest.skip(f"{_API_KEY_ENV} not set")
        if not _FIXTURE_PATH.exists():
            pytest.skip(
                f"Fixture not found: {_FIXTURE_PATH}. "
                "Run: python tests/integration/generate_archival_fixture.py"
            )

        fixture_data = _load_fixture()
        ctx_window = fixture_data["context_window"]
        fixture_tokens = fixture_data["total_tokens"]

        # The fixture stores the model name without litellm provider prefix.
        # Add "openai/" prefix for litellm routing to the OpenAI-compatible endpoint.
        model_name = "openai/" + fixture_data["model"]

        llm = CompletionClient(
            model=model_name,
            api_base=_API_BASE,
            api_key=api_key,
            temperature=0,
        )
        # litellm may not know this model — inject context_window via registry config.
        if llm.context_window is None:
            llm._registry_config = {"context_window": ctx_window}
        assert llm.context_window == ctx_window, (
            f"Model context_window mismatch: {llm.context_window} vs fixture {ctx_window}"
        )

        class A(Agent, llm=llm):
            async def respond(self, prompt: str) -> str:
                """Respond to {prompt}."""
                ...

        agent = A()

        # ── Load fixture: 95% of context window ────────────────────
        _hydrate_events(agent, fixture_data)
        n_events_loaded = len(list(agent.event_manager.keys()))
        assert n_events_loaded == fixture_data["n_events"], (
            f"Loaded {n_events_loaded} events, expected {fixture_data['n_events']}"
        )

        # Subscribe to Summary events (emitted by archival)
        summary_events: list = []
        agent.event_manager.on("Summary", lambda ev: summary_events.append(ev))

        # ── Phase 1: Call at 95% — should succeed, no archival ─────
        result1 = await agent.respond("Say hello in one word.")
        assert result1, "Phase 1: call should succeed at 95% fill"

        assert len(summary_events) == 0, (
            f"Phase 1: no archival expected (proactive clamp handles it), "
            f"got {len(summary_events)} Summary events"
        )

        # ── Phase 2: Overflow to ~105% → error → archive → succeed ─
        # Add enough events to push well past the context window.
        # Each event pair: ~300 words * 3 fields * 1.3 tok/word * 2 ≈ 2,340 tokens
        # Need ~26K more tokens (5% of 262K) → ~11 pairs. Add more to be safe.
        _add_overflow_events(agent, n_events=100, payload_words=300)

        n_events_before_phase2 = len(list(agent.event_manager.keys()))
        summary_events.clear()

        # Call the LLM — context is way over 100%. Proactive clamp drops messages.
        # If the API still rejects (litellm undercount), archival fires.
        result2 = await agent.respond("Say goodbye in one word.")
        assert result2, "Phase 2: call should eventually succeed"

        n_events_after = len(list(agent.event_manager.keys()))

        if len(summary_events) > 0:
            # ── Archival fired — verify invariants ──────────────────
            ev = summary_events[0]
            assert "context-window API error" in ev.summary_text, (
                f"Summary should mention API error: {ev.summary_text[:200]}"
            )
            assert ev.children_tags, "Summary must reference archived child tags"

            # Events decreased
            assert n_events_after < n_events_before_phase2, (
                f"Archival should reduce events: "
                f"{n_events_after} >= {n_events_before_phase2}"
            )

            # Check utilization after archival
            method = type(agent).respond
            llm_token = _current_llm_var.set(llm)
            method_token = _current_method_var.set(method)
            try:
                await agent.runtime._build_messages(
                    method, call_args=(agent, "x"), call_kwargs={}, tools=[]
                )
            finally:
                _current_llm_var.reset(llm_token)
                _current_method_var.reset(method_token)

            stats_post = agent.runtime._last_context_stats
            ratio = agent.runtime._token_calibration_ratio or 1.0
            effective_cap = int(ctx_window * 0.70 / max(ratio, 1.0))
            target_tok = int(effective_cap * _ARCHIVE_TARGET_UTILIZATION)

            # After archival, should be near 60% target (generous tolerance)
            assert stats_post.total_tokens <= target_tok * 1.50, (
                f"After archival: tokens={stats_post.total_tokens:,}, "
                f"target={target_tok:,} (60% of effective cap)"
            )
        else:
            # Proactive clamp was sufficient — no API error
            stats2 = agent.runtime._last_context_stats
            assert stats2 is not None
            cap = int(ctx_window * 0.70)
            assert stats2.total_tokens <= cap + 2000, (
                f"Clamp should keep tokens under cap: "
                f"{stats2.total_tokens:,} > {cap:,}"
            )

        # ── Calibration ratio should be learned ─────────────────────
        ratio = agent.runtime._token_calibration_ratio
        if ratio is not None:
            assert ratio > 0, f"Calibration ratio should be positive, got {ratio}"
