# SPDX-FileCopyrightText: Copyright (c) 2025, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Agent base class."""

import logging
from typing import TYPE_CHECKING, Annotated, Any, NamedTuple, cast
from uuid import uuid4

from agentdoc import hidden
from context_blocks import DynamicContext
from nemo_oo_agents.metaclass import AgentMeta
from nemo_oo_agents.runtime.context_vars import _parent_agent_var
from nemo_oo_agents.storage.markers import nosnapshot

if TYPE_CHECKING:
    from agentdoc.ext import TypeInfo
    from context_blocks.models import ContextWindowStats
    from context_blocks.render_config import RenderConfig
    from nemo_oo_agents.config.execution_config import ExecutionConfig
    from nemo_oo_agents.config.truncation_config import TruncationConfig
    from nemo_oo_agents.runtime.actor import ActorRuntime
    from nemo_oo_agents.runtime.context import ContextApi
    from nemo_oo_agents.runtime.context_manager import ContextManager
    from nemo_oo_agents.runtime.event_manager import EventManager
    from nemo_oo_agents.runtime.event_query import EventQuery
    from nemo_oo_agents.runtime.events import EventsApi
    from nemo_oo_agents.storage.manager import StorageManager
    from unifiedllm import UnifiedLLM

logger = logging.getLogger(__name__)

_auto_tracing_attempted = False


def _try_auto_enable_tracing() -> None:
    """Auto-enable OTLP tracing if the viewer is reachable. Called once per process."""
    global _auto_tracing_attempted
    if _auto_tracing_attempted:
        return
    _auto_tracing_attempted = True
    try:
        from openinference_instrumentation_nemo_oo_agents import enable_tracing

        enable_tracing()
    except ImportError:
        pass


# Internal sentinel for LLM cascading resolution
class _InheritSentinel:
    """Internal sentinel for LLM cascading resolution.

    NOT part of public API. Users should omit the llm parameter to enable cascading.
    This sentinel distinguishes "parameter omitted" from "parameter explicitly set to None".
    """

    def __repr__(self) -> str:
        return "INHERIT"


INHERIT = _InheritSentinel()


def _validate_llm_param(llm: object, class_name: str) -> None:
    """Validate the llm parameter for __init_subclass__ and __init__."""
    if llm is None:
        raise ValueError(
            f"{class_name}: llm=None is not allowed. "
            "To enable cascading, omit the llm parameter entirely. "
            "To use an explicit LLM, pass llm=my_llm."
        )


class FrameworkBlock(NamedTuple):
    """A framework context block definition.

    Args:
        value: The block value (static string or DynamicContext expression).
    """

    value: str | DynamicContext


class Agent(metaclass=AgentMeta):
    """
    Base class for all agents with automatic method wrapping.

    Agents can define async methods with ellipsis bodies that will be automatically
    generated by the LLM. Public methods are also automatically traced for observability.

    The framework handles infrastructure (event logging, execution, etc.).

    Framework attributes (all hidden from LLM, visible to devs):
        agent.context_manager — ContextManager: raw context block state
        agent.event_manager   — EventManager: event bus for callbacks and runtime use

    LLM-facing wrappers (always present, hidden by default; subclasses opt in via spec()):
        agent.context — ContextApi: dict-like API for managing prompt context blocks
        agent.events  — EventsApi: query past events by type, tag, or text

    For dev callbacks on LLM output:
        agent.event_manager.on("Message", my_handler)
        agent.event_manager.on("Reasoning", my_handler)
    """

    # Framework attributes — hidden from LLM, excluded from snapshots
    runtime: Annotated["ActorRuntime", hidden, nosnapshot]
    _storage: Annotated["StorageManager", hidden, nosnapshot]
    event_manager: Annotated["EventManager", hidden, nosnapshot]  # pyright: ignore[reportRedeclaration]
    context_manager: Annotated["ContextManager", hidden, nosnapshot]
    event_query: Annotated["EventQuery | None", hidden, nosnapshot]
    render_config: Annotated["RenderConfig", hidden, nosnapshot]
    _agent_id: Annotated[str, hidden, nosnapshot]
    _llm: Annotated["UnifiedLLM", hidden, nosnapshot]
    _truncation: Annotated["TruncationConfig", hidden, nosnapshot]
    _defined_methods_registry: Annotated[dict[str, str], hidden, nosnapshot]
    context: Annotated["ContextApi", hidden, nosnapshot]
    events: Annotated["EventsApi", hidden, nosnapshot]

    # Enable tracing for Agent classes (convention for metaclass)
    _enable_tracing = True

    # Framework context blocks — managed by _prepare_context(), protected from LLM mutation.
    # These use DynamicContext() so they are re-evaluated each LLM turn.
    # Each subclass gets its own copy via __init_subclass__, so mutations stay local.
    _framework_blocks: dict[str, "FrameworkBlock"] = {
        "system_prompt": FrameworkBlock(DynamicContext("self._system_prompt()")),
        "self": FrameworkBlock(DynamicContext("doc(self)")),
    }

    def __init_subclass__(
        cls,
        llm: "UnifiedLLM | _InheritSentinel" = INHERIT,
        truncation: "TruncationConfig | None" = None,
        execution: "ExecutionConfig | None" = None,
        context: "dict[str, str | DynamicContext | None] | None" = None,
        event_query: "EventQuery | None" = None,
        **kwargs: Any,
    ):
        """Configure agent class with metaclass.

        Args:
            llm: LLM client for this agent class. Omit to enable cascading.
            truncation: Optional truncation configuration for stdout/stderr/pprint limits.
            execution: ExecutionConfig for framework-level execution guards.
            context: Class-level context block overrides.
                - str: Static content
                - DynamicContext("expr"): DynamicContext expression, re-evaluated each turn
                - None: Remove block
            event_query: Default EventQuery for filtering events in context.
            **kwargs: Additional arguments for multiple inheritance support.
        """
        _validate_llm_param(llm, cls.__name__)

        super().__init_subclass__(**kwargs)

        # Give each subclass its own copy so mutations don't bleed to parent classes.
        if "_framework_blocks" not in cls.__dict__:
            cls._framework_blocks = dict(cls._framework_blocks)

        if llm is not INHERIT:
            cls._agent_llm = llm  # type: ignore[attr-defined]
        if truncation is not None:
            cls._agent_truncation = truncation  # type: ignore[attr-defined]
        if context is not None:
            cls._agent_context_blocks = context  # type: ignore[attr-defined]
        if event_query is not None:
            cls._agent_event_query = event_query  # type: ignore[attr-defined]

        from nemo_oo_agents.config.execution_config import ExecutionConfig as _EC

        cls._execution_config = execution or _EC()  # type: ignore[attr-defined]

    def __init__(
        self,
        llm: "UnifiedLLM | _InheritSentinel" = INHERIT,
        *,
        truncation: "TruncationConfig | None" = None,
        render_config: "RenderConfig | None" = None,
        context: "dict[str, str | DynamicContext | None] | None" = None,
        event_query: "EventQuery | None" = None,
        storage: "StorageManager | None" = None,
    ):
        """Initialize agent with its own runtime.

        Args:
            llm: LLM client to use. Omit to enable cascading resolution.
            truncation: Optional truncation configuration.
            render_config: RenderConfig for block/provider formatter selection.
            context: Instance-level context block overrides.
                - str: Static content
                - DynamicContext("expr"): DynamicContext expression, re-evaluated each turn
                - None: Remove block
            event_query: Instance-level EventQuery for filtering events in context.
            storage: Optional StorageManager for persistence. Defaults to
                InMemoryStorageManager (no persistence, same as current behavior).

        Core attributes (all hidden from LLM):
        - context_manager: ContextManager — raw context block state
        - event_manager: EventManager — event bus for callbacks
        - runtime: RuntimeServices provider (generate, execute_code)

        LLM-facing wrappers (always present, hidden from LLM by default):
        - context: ContextApi — dict-like prompt context API
        - events: EventsApi — query past events by type/tag/text
        """
        _try_auto_enable_tracing()

        _validate_llm_param(llm, self.__class__.__name__)

        # Deferred imports — these live here (not at module top) to break
        # circular dependencies between agent.py and the runtime package.
        from nemo_oo_agents.runtime.actor import ActorRuntime
        from nemo_oo_agents.runtime.context_manager import ContextManager
        from nemo_oo_agents.storage import InMemoryStorageManager

        # Generate agent ID
        self._agent_id = str(uuid4())

        # Registry for LLM-defined method source code (for snapshot serialization)
        self._defined_methods_registry: dict[str, str] = {}

        # Storage manager - default to InMemoryStorageManager (no persistence)
        self._storage = storage or InMemoryStorageManager()

        # Resolve LLM client with cascading resolution
        instance_llm = None if llm is INHERIT else llm
        self._llm = self._resolve_llm(instance_llm)

        # Resolve and store truncation config (with merge semantics)
        self._truncation = self._resolve_truncation(truncation)

        # Resolve render config (instance overrides class default)
        from context_blocks.render_config import RenderConfig as _RC

        self.render_config = render_config or _RC()

        # Resolve and store event query (instance overrides class-level)
        self.event_query = self._resolve_event_query(event_query)

        # Initialize context state (always present, hidden)
        self.context_manager = ContextManager(protected_keys=set(self._framework_blocks.keys()))

        # Apply class-level context blocks (from __init_subclass__)
        class_context = getattr(self.__class__, "_agent_context_blocks", None)
        if class_context:
            self._apply_context_dict(class_context)

        # Apply instance-level context blocks (overrides class-level)
        if context:
            self._apply_context_dict(context)

        # Create ContextApi and EventsApi wrappers (always present, hidden from LLM by default).
        # Subclasses opt in per-instance: spec(self, "context", hidden=False) in __init__.
        from nemo_oo_agents.runtime.context import ContextApi
        from nemo_oo_agents.runtime.events import EventsApi

        self.context = ContextApi(self)
        self.events = EventsApi(self)

        # Create runtime (manages execution, caching, signals)
        self.runtime = ActorRuntime(self)

    @hidden
    def _apply_context_dict(self, blocks: "dict[str, str | DynamicContext | None]") -> None:
        """Apply a dict of context block overrides.

        Used by __init__ to apply class-level and instance-level context.

        Args:
            blocks: Dict of overrides:
                - str: Static content
                - DynamicContext("expr"): DynamicContext expression
                - None: Remove block
        """
        for key, value in blocks.items():
            if value is None:
                self.context_manager.pop(key, None)
            elif isinstance(value, DynamicContext):
                self.context_manager.set_dynamic(key, value.expr)
            else:
                self.context_manager[key] = value

    @hidden
    def _resolve_llm(self, instance_llm: "UnifiedLLM | None") -> "UnifiedLLM":
        """Resolve which LLM to use via cascading resolution.

        Resolution order:
        1. Instance-level: MyAgent(llm=explicit_llm)
        2. Class hierarchy: class MyAgent(Agent, llm=class_llm) or inherited via MRO
        3. Runtime propagation: Parent agent via context variable
        4. Error: No LLM found

        Args:
            instance_llm: LLM passed to __init__, or None if INHERIT was used

        Returns:
            Resolved UnifiedLLM instance

        Raises:
            ValueError: If no LLM can be resolved through cascading
        """
        # 1. Instance-level explicit
        if instance_llm is not None:
            return instance_llm

        # 2. Class hierarchy (getattr walks the MRO automatically)
        class_llm = getattr(self.__class__, "_agent_llm", None)
        if class_llm is not None:
            return cast("UnifiedLLM", class_llm)

        # 3. Runtime parent propagation
        parent = _parent_agent_var.get()
        if parent is not None and hasattr(parent, "_llm"):
            return parent._llm

        # 4. No LLM found - provide helpful error
        raise ValueError(
            f"No LLM available for {self.__class__.__name__}. "
            f"Resolution attempted:\n"
            f"  1. Instance-level: Not provided\n"
            f"  2. Class hierarchy: Not set (checked full MRO)\n"
            f"  3. Runtime parent: No parent agent in context\n"
            f"\n"
            f"Solutions:\n"
            f"  - Pass llm=my_llm to __init__\n"
            f"  - Set llm=my_llm in class definition\n"
            f"  - Inherit from an Agent class with an LLM\n"
            f"  - Instantiate within a parent agent's generated code"
        )

    @hidden
    def _resolve_truncation(
        self, instance_truncation: "TruncationConfig | None"
    ) -> "TruncationConfig":
        """Resolve truncation config with merge semantics.

        Resolution order (earlier merged with later, later takes precedence):
        1. Default config (DEFAULT_TRUNCATION_CONFIG)
        2. Class-level: class MyAgent(Agent, truncation=...)
        3. Instance-level: MyAgent(truncation=...)

        Args:
            instance_truncation: Truncation config passed to __init__

        Returns:
            Resolved TruncationConfig after merging all levels
        """
        # Import at runtime to avoid circular dependency
        from nemo_oo_agents.config.truncation_config import DEFAULT_TRUNCATION_CONFIG

        # Start with default config
        config = DEFAULT_TRUNCATION_CONFIG

        # Merge class-level config if present
        class_truncation = getattr(self.__class__, "_agent_truncation", None)
        if class_truncation is not None:
            config = config.merge_with(class_truncation)

        # Merge instance-level config if present
        if instance_truncation is not None:
            config = config.merge_with(instance_truncation)

        return config

    @hidden
    def _resolve_event_query(
        self, instance_event_query: "EventQuery | None"
    ) -> "EventQuery | None":
        """Resolve event query with override semantics.

        Resolution order (later overrides earlier):
        1. Class-level: class MyAgent(Agent, event_query=...)
        2. Instance-level: MyAgent(event_query=...)

        Args:
            instance_event_query: EventQuery passed to __init__

        Returns:
            Resolved EventQuery or None if no query specified
        """
        # Instance-level overrides class-level
        if instance_event_query is not None:
            return instance_event_query

        # Check class-level
        class_event_query = getattr(self.__class__, "_agent_event_query", None)
        if class_event_query is not None:
            return cast("EventQuery", class_event_query)

        # No event query specified
        return None

    @property
    @hidden
    def agent_id(self) -> str:
        """Agent ID."""
        return self._agent_id

    @property  # type: ignore[no-redef]
    def event_manager(self) -> "EventManager":
        """Event manager — owned by the StorageManager."""
        return self._storage.event_manager

    @property
    @hidden
    def context_stats(self) -> "ContextWindowStats | None":
        """Most recent context window utilization stats, or None before first generation."""
        return self.runtime._last_context_stats

    @hidden
    def _system_prompt(self) -> str:
        """Generate the system prompt establishing agent identity.

        Override in subclasses to customize. The default prompt establishes
        the agent's identity and explains the interactive execution model.
        """
        return f"""You are {self.__class__.__name__}, a Python agent working in an interactive session.

## Context blocks
{self.render_config.block_formatter.format_description()}
"""

    # -------------------------------------------------------------------------
    # agentdoc protocol implementations
    # -------------------------------------------------------------------------

    @classmethod
    def __type_info__(cls) -> "TypeInfo":
        """Return TypeInfo for this Agent class, filtering framework internals.

        This method implements the agentdoc protocol for custom type introspection.
        It uses @hidden to determine what to show/hide, instead of underscore convention.

        Returns:
            TypeInfo with filtered fields and methods
        """
        import inspect

        from agentdoc.ext import TypeInfo, extract_callable_info, extract_type_info
        from agentdoc.visibility import is_hidden_field, is_hidden_method

        # Get base type info via automatic extraction (skip protocol to avoid recursion)
        base_info = extract_type_info(cls, _skip_protocol=True)

        # Build method list: dunder and single-underscore methods are hidden by default.
        # Use @shown to opt a _private method back in.
        seen_names: set[str] = set()
        all_methods = []
        for name, value in inspect.getmembers(cls, predicate=inspect.isfunction):
            if name.startswith("__") and name.endswith("__"):
                continue
            if name in seen_names:
                continue
            explicitly_shown = getattr(value, "_agentdoc_hidden", None) is False
            if name.startswith("_") and not explicitly_shown:
                continue
            raw = next(
                (vars(klass).get(name) for klass in cls.__mro__ if name in vars(klass)), None
            )
            if is_hidden_method(value) or (raw is not None and is_hidden_method(raw)):
                continue
            seen_names.add(name)
            all_methods.append(extract_callable_info(value))
        for name, value in inspect.getmembers(cls, predicate=inspect.ismethod):  # type: ignore[assignment]
            if name.startswith("__") and name.endswith("__"):
                continue
            if name in seen_names:
                continue
            explicitly_shown = getattr(value, "_agentdoc_hidden", None) is False
            if name.startswith("_") and not explicitly_shown:
                continue
            raw = next(
                (vars(klass).get(name) for klass in cls.__mro__ if name in vars(klass)), None
            )
            if is_hidden_method(value) or (raw is not None and is_hidden_method(raw)):
                continue
            seen_names.add(name)
            all_methods.append(extract_callable_info(value))
        source_order: dict[str, int] = {}
        idx = 0
        for klass in cls.__mro__:
            for name, value in klass.__dict__.items():
                try:
                    qualname = (
                        getattr(value, "__qualname__", None) or f"{klass.__qualname__}.{name}"
                    )
                except Exception:
                    qualname = f"{klass.__qualname__}.{name}"
                if qualname not in source_order:
                    source_order[qualname] = idx
                    idx += 1
        filtered_methods = sorted(all_methods, key=lambda m: source_order.get(m.name, idx))

        # Filter out @hidden fields (Annotated[T, hidden])
        filtered_fields = [f for f in base_info.fields if not is_hidden_field(cls, f.name)]

        return TypeInfo(
            name=base_info.name,
            base=base_info.base,
            fields=filtered_fields,
            methods=filtered_methods,
            docstring=base_info.docstring,
        )

    def __instance_values__(self) -> dict[str, Any]:
        """Return instance values, filtering framework attributes.

        This method implements the agentdoc protocol for custom instance value
        extraction. It returns only user-defined state, hiding framework internals.

        Includes both:
        - Instance attributes (from self.__dict__)
        - Class-level attributes like tools and child agent classes

        Returns:
            Dictionary of attribute name to value for documentation
        """
        import inspect

        from agentdoc.visibility import is_hidden_field, is_hidden_method

        values = {}

        # 1. Instance attributes from __dict__
        for name, value in self.__dict__.items():
            if is_hidden_field(self, name):
                continue
            # Keep non-callable values and classes (child agents); skip bound methods
            is_class = isinstance(value, type)
            if callable(value) and not is_class:
                continue
            values[name] = value

        # 2. Class-level attributes (tools, child agent classes, etc.)
        # getmembers_static avoids triggering descriptors during enumeration.
        for name, class_attr in inspect.getmembers_static(type(self)):
            if name in values or is_hidden_field(self, name):
                continue
            # @hidden @property / @hidden @cached_property: is_hidden_field only checks
            # Annotated markers; also check is_hidden_method (returns False for non-decorated).
            if is_hidden_method(class_attr):
                continue

            # Skip methods, classmethods, staticmethods
            if inspect.isfunction(class_attr) or inspect.ismethod(class_attr):
                continue
            if isinstance(class_attr, (classmethod, staticmethod)):
                continue

            # Resolve instance value (may differ from class_attr for descriptors)
            # Properties are included: call getattr on the live instance so their
            # computed value appears in doc(instance). Skip on any exception.
            try:
                value = getattr(self, name)
            except (AttributeError, TypeError):
                continue
            except Exception:
                logger.debug(
                    "Skipping attribute %r: getattr raised unexpectedly", name, exc_info=True
                )
                continue

            # Include classes (child agents) and non-callable values (tools, data)
            if isinstance(value, type) or not callable(value):
                values[name] = value

        return values
